// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBR4syxBkVNx-iE3p5-rTKFo-eOP1izLw',
    appId: '1:556292159430:web:3149fba8781f10ca48e4c7',
    messagingSenderId: '556292159430',
    projectId: 'chatapplication-f3d76',
    authDomain: 'chatapplication-f3d76.firebaseapp.com',
    storageBucket: 'chatapplication-f3d76.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6AqyboXT-ileMKxar49hylLBi-XLGWPw',
    appId: '1:556292159430:android:18c3efd6c6a6a63348e4c7',
    messagingSenderId: '556292159430',
    projectId: 'chatapplication-f3d76',
    storageBucket: 'chatapplication-f3d76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdiNu5msdn5ZohbDpSbFtv4_stYAFF6XY',
    appId: '1:556292159430:ios:d32dbe2b5256832b48e4c7',
    messagingSenderId: '556292159430',
    projectId: 'chatapplication-f3d76',
    storageBucket: 'chatapplication-f3d76.appspot.com',
    iosBundleId: 'com.example.chatapplication',
  );
}
